# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
summarization:
  enable: true
  method: "batch"
  llm:
    model: "meta/llama3-70b-instruct"
    max_tokens: 1024
  params:
    batch_size: 5
    batch_max_concurrency: 20
  prompts:
    caption: |
      You are an expert world understanding model. You are part of a complex machine learning pipeline that takes video of the worl and is helps visually impaired users understand and manipulate the world around them. 
      The videos are in first person view. Given the following description or query, your task is to search your video for that query and return a detailed response of all of what is requested. 
      Note relative locations in the video of objects, color, and anything else that may be helpful for someone to understand their surroundings. Search the video for the following
    caption_summarization: "You should summarize the following descriptions of a field of view in the format start_time:end_time:caption. The output should be bullet points in the format start_time:end_time: detailed_description. Don't return anything else except the bullet points. Always capture as much detailed information about object and scene descriptoins as possible."
    summary_aggregation: "You are an expert at describing visual scenes. Given the caption in the form start_time:end_time: caption, Aggregate the following captions in the format start_time:end_time:event_description. The output should only contain bullet points. Group output into logically similar categories. Preserve as much detail as possible."


#Write a concise and clear dense caption for the provided warehouse video, focusing on irregular or hazardous events such as boxes falling, workers not wearing PPE, workers falling, etc.